[PHP]
memory_limit=512M
upload_max_filesize=50M
post_max_size=50M

[opcache]
opcache.enable=0
; o usa esto si quieres mantenerlo activo:
; opcache.enable=1
; opcache.validate_timestamps=1
; opcache.revalidate_freq=0